server:
  port: 6061

spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 800
        max-wait: 10000
        max-idle: 20
        min-idle: 2
    timeout: 30000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
  cache:
    min-idle: 0
    type: redis